# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d015d6f7b2a35c1b0e9f14bb51be9b4c39d05385ae8d2d882144f44b77ab88fd4b7a425e083872eecfe7a4e5c1984740d477a86ac92a4bdd082992b6faa51bd

test:
  secret_key_base: d59d486aac608a232a2bf93094671610660a30e8b36bf420785ff37281ab486ed8d9939c6b8a328deda6dd077c66bb3c36b243257141047d868392f32823d0b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
